services:
  web:
    build:
      context: ./
      dockerfile: ./docker/dockerfile/Dockerfile
    depends_on:
      - sus-db
    ports:
      - "8075:8074"
      - "8073:8073"
    networks:
      - web
    environment:
    - HOST=sus-db
    - USER=odoo
    - PASSWORD=asdjkl123
    restart: always
    volumes:
      - sus-odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
  sus-db:
    image: postgres:12.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=asdjkl123
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - web
    volumes:
      - sus-db-data:/var/lib/postgresql/data/pgdata
  sus-pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=luiesus@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=asdjkl123
    volumes:
      - sus-pgadmin4-data:/var/lib/pgadmin
    depends_on:
      - sus-db
    ports:
      - "81:80"
    networks:
      - web
    restart: always
    links:
      - sus-db

volumes:
  sus-odoo-web-data:
  sus-pgadmin4-data:
  sus-db-data:
      
networks:
  web:
    external: true