services:
  planod:
    build:
      context: ./
      dockerfile: ./docker/dockerfile/Dockerfile
    depends_on:
      - plan-db-3
    networks:
      - web
    environment:
    - HOST=plan-db-3
    - USER=odoo
    - PASSWORD=asdjkl123
    - TZ=America/Argentina/Buenos_Aires
    container_name: plan-odoo
    labels:
    - traefik.enable=true
    - traefik.http.routers.plan-odoo.rule=Host(`planificador.luisesp.cloud`)
    #- traefik.http.routers.plan-odoo.entrypoints=web-secured
    #- traefik.http.routers.plan-odoo.tls=true
    #- traefik.http.routers.plan-odoo.tls.certresolver=lets-encrypt
    - traefik.http.services.plan-odoo.loadbalancer.server.port=8069
    volumes:
      - pla-odoo-web-data:/var/lib/odooPl
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-backups:/var/lib/odoo/backups/plano-db
  plan-db-3:
    image: postgres:12.5
    container_name: plan-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=asdjkl123
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresqlPl/data/pgdata
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - web
    volumes:
      - plan-db-3-data:/var/lib/postgresqlPl/data/pgdata
  sus-pgadmin:
    image: dpage/pgadmin4
    container_name: plan-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=luiesp27@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=asdjkl123
    volumes:
      - sus-pgadmin4-data:/var/lib/pgadmin
    depends_on:
      - plan-db-3
    networks:
      - web
    restart: always
    links:
      - plan-db-3
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadminpl.rule=Host(`planadmin.luisesp.cloud`)
      #- traefik.http.routers.pgadminpl.entrypoints=web-secured
      #- traefik.http.routers.pgadminpl.tls=true
      - traefik.http.services.pgadminpl.loadbalancer.server.port=80

volumes:
  pla-odoo-web-data:
  sus-pgadmin4-data:
  plan-db-3-data:
  odoo-backups:
      
networks:
  web:
    external: true